services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: haslo123
      POSTGRES_DB: mojadb